import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardLayout from "./dashboard/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Agsa Portal University Dashboard",
  description: "Generated by Agsa Portal",
  icons: {
    icon: "https://api.agsapakistan.com/resources/new_logo.svg", // Your logo URL
    apple: "https://api.agsapakistan.com/resources/new_logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
